codecov:
  notify:
    require_ci_to_pass: false
    # countdown: 15
    # delay: 15
    after_n_builds: 1  # send notifications and complete cc build after 1 upload

coverage:
  status:
    project: false
    patch:
      default:
        target: 80%

comment: false